TRAIN:
    arch: 'resnet50'
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
    print_freq: 10
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    start_epoch: 0
    epochs: 15
    lr_epochs: [0,1,15]
    lr_values: [0,0.4,0.04]
    half: true
    random_init: true
ADV:
    adv_train: pgd
    clip_eps: 2.0
    fgsm_step: 2.5
    pgd_alpha: 0.8
    pgd_steps: 7
    n_repeats: 1
    pgd_attack: 
    - [10, 0.00392156862]
    - [50, 0.00392156862]
DATA:
    workers: 16
    max_color_value: 255.0
    img_size: 0
    batch_size: 128
    crop_size: 288
# ...existing code...